name: CI

on:
  pull_request:
  push:

jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install StyLua
        uses: JohnnyMorganz/stylua-action@v5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            version: latest
            args: --check ./
